In [34]:
import numpy as np
from sklearn.model_selection import RepeatedKFold

In [26]:
X = np.array([[1, 2], [3, 4], [5, 6], [7, 8]])
y = np.array([0, 1, 2, 3])
rkf = RepeatedKFold(n_splits=2, n_repeats=2, random_state=2652124)
for train_index, test_index in rkf.split(X):
    print("TRAIN:", train_index, "TEST:", test_index)
    X_train, X_test = X[train_index], X[test_index]
    y_train, y_test = y[train_index], y[test_index]
    print('----')

TRAIN: [0 1] TEST: [2 3]
----
TRAIN: [2 3] TEST: [0 1]
----
TRAIN: [1 2] TEST: [0 3]
----
TRAIN: [0 3] TEST: [1 2]
----


In [27]:
X_train

array([[1, 2],
       [7, 8]])

In [28]:
X_test

array([[3, 4],
       [5, 6]])

In [29]:
y_train

array([0, 3])

In [30]:
y_test

array([1, 2])

In [31]:
X[[0,3]]

array([[1, 2],
       [7, 8]])

In [32]:
X[[1,3]]

array([[3, 4],
       [7, 8]])