In [1]:
import numpy as np
import pandas as pd
from sklearn.linear_model import LinearRegression

In [2]:
inp=pd.DataFrame(columns=['rad','q','r'])
inp

Empty DataFrame
Columns: [rad, q, r]
Index: []

In [3]:
out=pd.DataFrame(columns=['nq','nr'])
out

Empty DataFrame
Columns: [nq, nr]
Index: []

In [4]:
rows = [
    pd.Series(data={'rad':2,'q':5,'r':-2,'nq':1,'nr':-1}),
    pd.Series(data={'rad':2,'q':2,'r':3,'nq':1,'nr':0}),
    pd.Series(data={'rad':2,'q':-3,'r':5,'nq':0,'nr':1}),
    pd.Series(data={'rad':2,'q':-5,'r':2,'nq':-1,'nr':1}),
    pd.Series(data={'rad':2,'q':-2,'r':-3,'nq':-1,'nr':0}),
    pd.Series(data={'rad':2,'q':3,'r':-5,'nq':0,'nr':-1}),
]
rows

[rad    2
 q      5
 r     -2
 nq     1
 nr    -1
 dtype: int64,
 rad    2
 q      2
 r      3
 nq     1
 nr     0
 dtype: int64,
 rad    2
 q     -3
 r      5
 nq     0
 nr     1
 dtype: int64,
 rad    2
 q     -5
 r      2
 nq    -1
 nr     1
 dtype: int64,
 rad    2
 q     -2
 r     -3
 nq    -1
 nr     0
 dtype: int64,
 rad    2
 q      3
 r     -5
 nq     0
 nr    -1
 dtype: int64]

In [5]:
for r in rows:
    inp.loc[len(inp)]=r
    out.loc[len(out)]=r
print(inp)
print(out)

   rad  q  r
0    2  5 -2
1    2  2  3
2    2 -3  5
3    2 -5  2
4    2 -2 -3
5    2  3 -5
   nq  nr
0   1  -1
1   1   0
2   0   1
3  -1   1
4  -1   0
5   0  -1


In [6]:
reg=LinearRegression().fit(inp,out)

In [7]:
print(f'{reg.coef_} {reg.intercept_}')
reg.coef_

[[ 0.          0.26315789  0.15789474]
 [ 0.         -0.15789474  0.10526316]] [0. 0.]


array([[ 0.        ,  0.26315789,  0.15789474],
       [ 0.        , -0.15789474,  0.10526316]])

In [8]:
np.round(reg.predict(inp))

array([[ 1., -1.],
       [ 1., -0.],
       [-0.,  1.],
       [-1.,  1.],
       [-1.,  0.],
       [ 0., -1.]])

In [9]:
reg.score(inp,out)

1.0

In [10]:
reg.predict([[2,6,-10],[2,1,-8],[2,4,-13],[2,3,-24]]).astype(int)

/home/tejag/.local/lib/python3.10/site-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([[ 0, -1],
       [ 0,  0],
       [ 0, -1],
       [-2, -2]])

In [11]:
reg.predict([[5,5,6],[5,11,-5],[5,6,-11]]).astype(int)

/home/tejag/.local/lib/python3.10/site-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([[ 2,  0],
       [ 2, -2],
       [ 0, -2]])

In [21]:
qx=0.26315789
qy=0.15789474

rx=-0.15789474
ry=0.10526316

In [22]:
q=6
r=-10
print(q*qx+r*qy)
print(q*rx+r*ry)

-6.000000007944095e-08
-2.0000000399999998


In [23]:
q=1
r=-8
print(q*qx+r*qy)
print(q*rx+r*ry)

-1.00000003
-1.0000000199999999
