In [20]:
import torch
from torch import nn
import numpy as np

In [21]:
def makeTensor(size):
    np.random.seed(0)
    nums = [np.random.randint(0xFFFFFFFF)/0xFFFFFFFF for i in range(torch.Size(size).numel())]
    return torch.Tensor(nums).reshape(size)

In [17]:
# conv(makeTensor((1, 3, 3)))

tensor([[[29.8410]]], grad_fn=<SqueezeBackward1>)

In [31]:
def test2Inp1Out():
    conv = torch.nn.Conv2d(2, 1, 3)
    weights = torch.as_tensor([x + 1.0 for x in range(2 * 3 * 3)]).reshape((1, 2, 3, 3))
    with torch.no_grad():
        conv.weight = nn.Parameter(weights)
    inp = torch.as_tensor([x + 1.0 for x in range(2 * 3 * 3)]).reshape((1, 2, 3, 3))
    out = conv(inp)
    print(out)
test2Inp1Out()

In [47]:
def test2Inp2Out():
    conv = torch.nn.Conv2d(2, 2, 3, bias=False)
    weights = torch.as_tensor([x + 1.0 for x in range(2 * 2 * 3 * 3)]).reshape((2, 2, 3, 3))
    with torch.no_grad():
        conv.weight = nn.Parameter(weights)
    inp = torch.as_tensor([x + 1.0 for x in range(2 * 3 * 3)]).reshape((1, 2, 3, 3))
    out = conv(inp)
    print(out)
test2Inp2Out()

tensor([[[[2109.]],

         [[5187.]]]], grad_fn=<ConvolutionBackward0>)


In [45]:
def test2Inp2Out2Groups():
    conv = torch.nn.Conv2d(2, 2, 3, groups=2, bias=False)
    with torch.no_grad():
        weights = torch.as_tensor([x + 1.0 for x in range(2 * 1 * 3 * 3)]).reshape((2, 1, 3, 3))
        conv.weight = nn.Parameter(weights)
    inp = torch.as_tensor([x + 1.0 for x in range(2 * 3 * 3)]).reshape((1, 2, 3, 3))
    out = conv(inp)
    print(out)
test2Inp2Out2Groups()

tensor([[[[ 285.]],

         [[1824.]]]], grad_fn=<ConvolutionBackward0>)
