In [1]:
import torch

In [11]:
data = [x for x in range(2 * 3 * 4)]
t = torch.as_tensor(data).reshape((2, 3, 4))
t

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])

In [12]:
t.permute((2, 1, 0))

tensor([[[ 0, 12],
         [ 4, 16],
         [ 8, 20]],

        [[ 1, 13],
         [ 5, 17],
         [ 9, 21]],

        [[ 2, 14],
         [ 6, 18],
         [10, 22]],

        [[ 3, 15],
         [ 7, 19],
         [11, 23]]])

In [15]:
data1 = [x for x in range(2 * 2)]
t1 = torch.as_tensor(data1).reshape((2, 2))
t1

tensor([[0, 1],
        [2, 3]])

In [16]:
t1.permute((1, 0))

tensor([[0, 2],
        [1, 3]])

In [29]:
data2 = [x for x in range(2 * 3 * 4 * 5 * 6 * 7)]
t2 = torch.as_tensor(data2).reshape((2, 3, 4, 5, 6, 7))
print(t2.shape)
print(t2.stride())

torch.Size([2, 3, 4, 5, 6, 7])
(2520, 840, 210, 42, 7, 1)


In [30]:
t2 = t2.permute((5, 4, 3, 2, 1, 0))
t2.shape

torch.Size([7, 6, 5, 4, 3, 2])

In [31]:
t2.stride()

(1, 7, 42, 210, 840, 2520)

In [32]:
3 * 4* 5 * 6 * 7

2520