In [57]:
import numpy as np
from sklearn import metrics, preprocessing

In [58]:
x2=np.array([[1,1],[1,2],[2,2],[0,1]])
print(x2)
y2=preprocessing.normalize(x2,norm='l1')
print(y2)
print(y2.sum(axis=0))
print(y2.sum(axis=1))

[[1 1]
 [1 2]
 [2 2]
 [0 1]]
[[0.5        0.5       ]
 [0.33333333 0.66666667]
 [0.5        0.5       ]
 [0.         1.        ]]
[1.33333333 2.66666667]
[1. 1. 1. 1.]


In [59]:
x2=np.array([[1,1],[1,2],[2,2],[0,1]])
print(x2)
y2=preprocessing.normalize(x2,norm='l2')
print(y2)
print(y2.sum(axis=0))
print(y2.sum(axis=1))

[[1 1]
 [1 2]
 [2 2]
 [0 1]]
[[0.70710678 0.70710678]
 [0.4472136  0.89442719]
 [0.70710678 0.70710678]
 [0.         1.        ]]
[1.86142716 3.30864075]
[1.41421356 1.34164079 1.41421356 1.        ]


In [64]:
1/np.sqrt(4)

0.5