In [26]:
import numpy as np

In [27]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
# Convert to 2D np.array
x.reshape(1,10)

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [29]:
# Reshape into 2D np.array
x.reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [34]:
# Convert to 2D np.array
x.reshape(1,-1)

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [35]:
x.reshape(1,-2)

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [14]:
# Convert to 2D np.array
y = x.reshape(1,10)
y

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [21]:
x.reshape(10,1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [37]:
x.reshape(2,-1)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [38]:
x.reshape(5,-1)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])