In [3]:
import numpy as np
import pandas as pd
from sklearn.linear_model import LinearRegression

In [4]:
inp=pd.DataFrame(columns=['q','r'])
inp

Empty DataFrame
Columns: [q, r]
Index: []

In [5]:
out=pd.DataFrame(columns=['nq','nr'])
out

Empty DataFrame
Columns: [nq, nr]
Index: []

In [6]:
rows = [
    pd.Series(data={'q':5,'r':-2,'nq':1,'nr':-1}),
    pd.Series(data={'q':2,'r':3,'nq':1,'nr':0}),
    pd.Series(data={'q':-3,'r':5,'nq':0,'nr':1}),
    pd.Series(data={'q':-5,'r':2,'nq':-1,'nr':1}),
    pd.Series(data={'q':-2,'r':-3,'nq':-1,'nr':0}),
    pd.Series(data={'q':3,'r':-5,'nq':0,'nr':-1}),
]
rows

[q     5
 r    -2
 nq    1
 nr   -1
 dtype: int64,
 q     2
 r     3
 nq    1
 nr    0
 dtype: int64,
 q    -3
 r     5
 nq    0
 nr    1
 dtype: int64,
 q    -5
 r     2
 nq   -1
 nr    1
 dtype: int64,
 q    -2
 r    -3
 nq   -1
 nr    0
 dtype: int64,
 q     3
 r    -5
 nq    0
 nr   -1
 dtype: int64]

In [7]:
for r in rows:
    inp.loc[len(inp)]=r
    out.loc[len(out)]=r
print(inp)
print(out)

   q  r
0  5 -2
1  2  3
2 -3  5
3 -5  2
4 -2 -3
5  3 -5
   nq  nr
0   1  -1
1   1   0
2   0   1
3  -1   1
4  -1   0
5   0  -1


In [8]:
reg=LinearRegression().fit(inp,out)

In [9]:
print(f'{reg.coef_} {reg.intercept_}')
reg.coef_

[[ 0.26315789  0.15789474]
 [-0.15789474  0.10526316]] [0. 0.]


array([[ 0.26315789,  0.15789474],
       [-0.15789474,  0.10526316]])

In [15]:
np.round(reg.predict(inp))

array([[ 1., -1.],
       [ 1.,  0.],
       [ 0.,  1.],
       [-1.,  1.],
       [-1., -0.],
       [-0., -1.]])

In [16]:
reg.score(inp,out)

1.0

In [18]:
reg.predict([[6,-10],[1,-8],[4,-13],[3,-24]]).astype(int)

/home/tejag/.local/lib/python3.10/site-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([[ 0, -2],
       [-1, -1],
       [-1, -2],
       [-3, -3]])

In [21]:
qx=0.26315789
qy=0.15789474

rx=-0.15789474
ry=0.10526316

In [22]:
q=6
r=-10
s=4
print(q*qx+r*qy)
print(q*rx+r*ry)

-6.000000007944095e-08
-2.0000000399999998


In [23]:
q=1
r=-8
s=7
print(q*qx+r*qy)
print(q*rx+r*ry)

-1.00000003
-1.0000000199999999
