In [9]:
import numpy as np
import pandas as pd
from sklearn.linear_model import LinearRegression

In [19]:
inp=pd.DataFrame(columns=['q','r','s'])
inp

Empty DataFrame
Columns: [q, r, s]
Index: []

In [20]:
out=pd.DataFrame(columns=['nq','nr'])
out

Empty DataFrame
Columns: [nq, nr]
Index: []

In [21]:
rows = [
    pd.Series(data={'q':5,'r':-2,'s':-3,'nq':1,'nr':-1}),
    pd.Series(data={'q':2,'r':3,'s':-5,'nq':1,'nr':0}),
    pd.Series(data={'q':-3,'r':5,'s':-2,'nq':0,'nr':1}),
    pd.Series(data={'q':-5,'r':2,'s':3,'nq':-1,'nr':1}),
    pd.Series(data={'q':-2,'r':-3,'s':5,'nq':-1,'nr':0}),
    pd.Series(data={'q':3,'r':-5,'s':2,'nq':0,'nr':-1}),
]
rows

[q     5
 r    -2
 s    -3
 nq    1
 nr   -1
 dtype: int64,
 q     2
 r     3
 s    -5
 nq    1
 nr    0
 dtype: int64,
 q    -3
 r     5
 s    -2
 nq    0
 nr    1
 dtype: int64,
 q    -5
 r     2
 s     3
 nq   -1
 nr    1
 dtype: int64,
 q    -2
 r    -3
 s     5
 nq   -1
 nr    0
 dtype: int64,
 q     3
 r    -5
 s     2
 nq    0
 nr   -1
 dtype: int64]

In [22]:
for r in rows:
    inp.loc[len(inp)]=r
    out.loc[len(out)]=r
print(inp)
print(out)

   q  r  s
0  5 -2 -3
1  2  3 -5
2 -3  5 -2
3 -5  2  3
4 -2 -3  5
5  3 -5  2
   nq  nr
0   1  -1
1   1   0
2   0   1
3  -1   1
4  -1   0
5   0  -1


In [23]:
reg=LinearRegression().fit(inp,out)

In [28]:
print(f'{reg.coef_} {reg.intercept_}')
reg.coef_

[[ 0.12280702  0.01754386 -0.14035088]
 [-0.14035088  0.12280702  0.01754386]] [0. 0.]


array([[ 0.12280702,  0.01754386, -0.14035088],
       [-0.14035088,  0.12280702,  0.01754386]])

In [30]:
reg.predict(inp)

array([[ 1.00000000e+00, -1.00000000e+00],
       [ 1.00000000e+00, -6.93889390e-17],
       [-5.55111512e-17,  1.00000000e+00],
       [-1.00000000e+00,  1.00000000e+00],
       [-1.00000000e+00,  6.93889390e-17],
       [ 5.55111512e-17, -1.00000000e+00]])