In [1]:
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
# x should be of shape (n_sample,n_features)
x = np.arange(0, 100).reshape(-1,1)
x

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24],
       [25],
       [26],
       [27],
       [28],
       [29],
       [30],
       [31],
       [32],
       [33],
       [34],
       [35],
       [36],
       [37],
       [38],
       [39],
       [40],
       [41],
       [42],
       [43],
       [44],
       [45],
       [46],
       [47],
       [48],
       [49],
       [50],
       [51],
       [52],
       [53],
       [54],
       [55],
       [56],
       [57],
       [58],
       [59],
       [60],
       [61],
       [62],
       [63],
       [64],
       [65],
       [66],
       [67],
       [68],
       [69],
       [70],
       [71],
       [72],
       [73],
       [74],
       [75],
       [76],

In [3]:
y = x * 2 + 5
y

array([[  5],
       [  7],
       [  9],
       [ 11],
       [ 13],
       [ 15],
       [ 17],
       [ 19],
       [ 21],
       [ 23],
       [ 25],
       [ 27],
       [ 29],
       [ 31],
       [ 33],
       [ 35],
       [ 37],
       [ 39],
       [ 41],
       [ 43],
       [ 45],
       [ 47],
       [ 49],
       [ 51],
       [ 53],
       [ 55],
       [ 57],
       [ 59],
       [ 61],
       [ 63],
       [ 65],
       [ 67],
       [ 69],
       [ 71],
       [ 73],
       [ 75],
       [ 77],
       [ 79],
       [ 81],
       [ 83],
       [ 85],
       [ 87],
       [ 89],
       [ 91],
       [ 93],
       [ 95],
       [ 97],
       [ 99],
       [101],
       [103],
       [105],
       [107],
       [109],
       [111],
       [113],
       [115],
       [117],
       [119],
       [121],
       [123],
       [125],
       [127],
       [129],
       [131],
       [133],
       [135],
       [137],
       [139],
       [141],
       [143],
       [145],
      

In [4]:
reg = LinearRegression().fit(x, y)

In [5]:
reg.score(x, y)

1.0

In [6]:
reg.predict(x)

array([[  5.],
       [  7.],
       [  9.],
       [ 11.],
       [ 13.],
       [ 15.],
       [ 17.],
       [ 19.],
       [ 21.],
       [ 23.],
       [ 25.],
       [ 27.],
       [ 29.],
       [ 31.],
       [ 33.],
       [ 35.],
       [ 37.],
       [ 39.],
       [ 41.],
       [ 43.],
       [ 45.],
       [ 47.],
       [ 49.],
       [ 51.],
       [ 53.],
       [ 55.],
       [ 57.],
       [ 59.],
       [ 61.],
       [ 63.],
       [ 65.],
       [ 67.],
       [ 69.],
       [ 71.],
       [ 73.],
       [ 75.],
       [ 77.],
       [ 79.],
       [ 81.],
       [ 83.],
       [ 85.],
       [ 87.],
       [ 89.],
       [ 91.],
       [ 93.],
       [ 95.],
       [ 97.],
       [ 99.],
       [101.],
       [103.],
       [105.],
       [107.],
       [109.],
       [111.],
       [113.],
       [115.],
       [117.],
       [119.],
       [121.],
       [123.],
       [125.],
       [127.],
       [129.],
       [131.],
       [133.],
       [135.],
       [13

In [10]:
reg.rank_

1

In [11]:
reg.get_params(deep=True)

{'copy_X': True,
 'fit_intercept': True,
 'n_jobs': None,
 'normalize': 'deprecated',
 'positive': False}