In [1]:
import numpy as np
from sklearn.linear_model import LinearRegression

In [3]:
x = np.arange(1,10).reshape(-1,1)
x

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [10]:
y = np.concatenate([x*2+5,x*3+1],axis=1)
y

array([[ 7,  4],
       [ 9,  7],
       [11, 10],
       [13, 13],
       [15, 16],
       [17, 19],
       [19, 22],
       [21, 25],
       [23, 28]])

In [11]:
mod = LinearRegression().fit(x,y)

In [12]:
mod.predict(x)

array([[ 7.,  4.],
       [ 9.,  7.],
       [11., 10.],
       [13., 13.],
       [15., 16.],
       [17., 19.],
       [19., 22.],
       [21., 25.],
       [23., 28.]])

In [13]:
mod.score(x,y)

1.0