In [61]:
import numpy as np
from sklearn.linear_model import Lasso,LinearRegression

In [62]:
x=np.array([[1.0,0.26511257647147524],[2.0,0.25446007380778213],[3.0,0.4342724196284832],[4.0,0.3335906988650903],[5.0,0.5375828312580055],[6.0,0.3504721583867916],[7.0,0.805892886754213],[8.0,0.875970600535897],[9.0,0.36811269451273865],[10.0,0.3034514558654112]])
x

array([[ 1.        ,  0.26511258],
       [ 2.        ,  0.25446007],
       [ 3.        ,  0.43427242],
       [ 4.        ,  0.3335907 ],
       [ 5.        ,  0.53758283],
       [ 6.        ,  0.35047216],
       [ 7.        ,  0.80589289],
       [ 8.        ,  0.8759706 ],
       [ 9.        ,  0.36811269],
       [10.        ,  0.30345146]])

In [63]:
y = x[:,0] * 5 + 2
y

array([ 7., 12., 17., 22., 27., 32., 37., 42., 47., 52.])

In [64]:
model = Lasso(alpha=0.15, max_iter=10000)
model.fit(x, y)

Lasso(alpha=0.15, max_iter=10000)

In [65]:
model.coef_

array([4.98181818, 0.        ])

In [66]:
model.intercept_

2.1000000000000014

In [67]:
model.score(x,y)

0.9999867768595041

In [68]:
model.predict(x)

array([ 7.08181818, 12.06363636, 17.04545455, 22.02727273, 27.00909091,
       31.99090909, 36.97272727, 41.95454545, 46.93636364, 51.91818182])