In [12]:
import tensorflow as tf
sess_cpu = tf.compat.v1.Session(config=tf.compat.v1.ConfigProto(device_count={'GPU': 0}))

In [59]:
model = Sequential([
    Dense(1, activation=keras.activations.linear, input_shape=[1]),
])
model.compile(loss='mse', optimizer='rmsprop')

In [60]:
x = np.random.randint(0, 50, 1000)
#x = np.array([8, 0, 2, 1, 9, 5, 2, 5, 0, 4, 5, 9, 9, 2, 4, 9, 7, 9, 0, 7, 5, 4, 0, 3, 4, 7, 2, 2, 5, 4, 2, 2, 4, 8, 1, 9, 4, 4, 0, 9, 2, 9, 3, 0, 0, 5, 6, 3, 5, 5, 8, 5, 0, 0, 4, 8, 7, 3, 1, 2, 2, 8, 0, 3, 9, 9, 4, 2, 3, 9, 4, 7, 4, 6, 8, 6, 3, 8, 1, 3, 2, 2, 0, 7, 9, 9, 3, 8, 9, 2, 2, 0, 7, 4, 8, 3, 9, 6, 4, 7])
x

array([ 7, 35, 13, 31, 49, 42, 47, 41, 21,  3, 18, 35,  1,  5, 46, 45, 44,
       39, 33, 16, 45, 14, 48, 29,  4, 14,  4,  2, 13, 15, 11, 12, 29, 21,
       32, 11, 15, 38, 21, 32, 42, 26, 10, 26,  5,  3, 38, 17, 32, 11, 20,
       47,  7, 37, 42, 15, 10, 47, 42, 43, 49, 38, 41,  9, 10, 35, 12,  3,
       48, 38, 35, 44, 31,  6, 13, 41, 39, 14, 47, 14,  4, 27, 24, 38,  8,
        2, 44, 25, 27, 33, 34, 31,  8,  9,  1, 32, 47, 30, 14,  1,  3, 34,
       27, 11,  9,  2, 35, 18, 10,  6, 10,  3, 41,  5,  6,  7, 22, 38, 14,
        0, 16, 12, 40, 36, 17, 43, 20, 20, 13,  0,  2, 39, 27, 41, 35, 13,
        9,  5,  7, 11, 13,  6, 22, 37, 42, 20,  1, 22, 42, 33,  1, 26, 37,
       37, 25, 15, 11, 36, 48,  2, 14,  8, 17,  6, 12, 44, 17, 27, 13, 46,
       43, 27, 33, 33, 46,  3, 45, 34, 41, 41, 20, 29, 23, 44,  5,  6, 44,
       10,  6, 42, 20, 14, 39, 47, 21, 45, 15, 38, 32, 40, 46, 34, 20, 32,
       21,  2, 19,  1, 23, 27, 34, 29,  9, 12,  5, 33, 42, 26, 37, 47, 42,
       48, 48,  3, 17,  5

In [61]:
y = x * 5 + 2
y

array([ 37, 177,  67, 157, 247, 212, 237, 207, 107,  17,  92, 177,   7,
        27, 232, 227, 222, 197, 167,  82, 227,  72, 242, 147,  22,  72,
        22,  12,  67,  77,  57,  62, 147, 107, 162,  57,  77, 192, 107,
       162, 212, 132,  52, 132,  27,  17, 192,  87, 162,  57, 102, 237,
        37, 187, 212,  77,  52, 237, 212, 217, 247, 192, 207,  47,  52,
       177,  62,  17, 242, 192, 177, 222, 157,  32,  67, 207, 197,  72,
       237,  72,  22, 137, 122, 192,  42,  12, 222, 127, 137, 167, 172,
       157,  42,  47,   7, 162, 237, 152,  72,   7,  17, 172, 137,  57,
        47,  12, 177,  92,  52,  32,  52,  17, 207,  27,  32,  37, 112,
       192,  72,   2,  82,  62, 202, 182,  87, 217, 102, 102,  67,   2,
        12, 197, 137, 207, 177,  67,  47,  27,  37,  57,  67,  32, 112,
       187, 212, 102,   7, 112, 212, 167,   7, 132, 187, 187, 127,  77,
        57, 182, 242,  12,  72,  42,  87,  32,  62, 222,  87, 137,  67,
       232, 217, 137, 167, 167, 232,  17, 227, 172, 207, 207, 10

In [62]:
model.fit(x, y)

32/32 [==============================] - 0s 471us/step - loss: 10713.2793


In [63]:
model.predict([8])

array([[11.091156]], dtype=float32)